version: '2'

services:
  service:
    image: munch-data/service:4.0
    environment:
      - SERVICE_MUNCH_DATA_ELASTIC_URL=http://elastic:9200
      - SERVICE_MUNCH_DATA_ELASTIC_IAM_SIGNING=false
      - SERVICE_MUNCH_DATA_DYNAMODB_URL=http://dynamodb:8000
    ports:
      - "8052:8000"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - "8050:9200"

  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    ports:
      - "8051:8000"
