version: '2'

services:
  munch-db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=K851xsSffyTJP3e1M7rd
    ports:
      - 5444:5432
  munch-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200
  search:
    image: munch-core/service-search
    environment:
      - SERVICE_ELASTIC_URL=http://munch-es:9200
    ports:
      - "8701:8000"

  # Munch Catalyst
  munch-catalyst:
    image: munch-core/catalyst-munch
    environment:
      - SERVICE_DATA_URL=http://proxy.corpus.munch.space:8200
      - MUNCH_CATALYST_SLEEP=100h

      - MUNCH_SERVICE_DATA_URL=http://10.0.75.1:8700
      - MUNCH_SERVICE_SEARCH_URL=http://search:8000
    env_file: H:/docker/munch-core.env

  # Munch Api
  munch-api:
    image: munch-core/service-api
    environment:
      - MUNCH_SERVICE_DATA_URL=http://10.0.75.1:8700
      - MUNCH_SERVICE_SEARCH_URL=http://search:8000
      - SERVICE_NOMINATIM_URL=http://nominatim:8080

      - MUNCH_API_SUPPORTED_BUILDS=1
      - MUNCH_API_SUPPORTED_VERSIONS=1
    ports:
      - "8800:8000"
  nominatim:
    image: fuxingloh/nominatim-docker-singapore:2.5
    ports:
      - "9888:8080"



